POST http://localhost:8080/recipes
Content-Type: application/json

{
  "recipeName": "Pizza",
  "ingredients": [
    {
      "name": "Flour",
      "weight": 500,
      "type": "DRY"
    },
    {
      "name": "Salt",
      "weight": 13,
      "type": "DRY"
    },
    {
      "name": "water",
      "weight": 300,
      "type": "DRY"
    }
  ]
}

###

GET http://localhost:8080/recipes/3
Content-Type: application/json

###

GET http://localhost:8080/recipes
Content-Type: application/json

###

DELETE http://localhost:8080/recipes/3
